name: photo-culling-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - pip:
    - jupyter
    - langgraph
    - langchain
    - openai
    - python-dotenv
    - gradio
    - pytest
    - pytest-mock 